package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.08 22:08:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class DateTest {



  // Generated by ComTest BEGIN
  /** testLuo71 */
  @Test
  public void testLuo71() {    // Date: 71
    Date pv1 = new Date(); 
    assertEquals("From: Date line: 73", 0, pv1.getId()); 
    pv1.luo(); 
    Date pv2 = new Date(); 
    pv2.luo(); 
    int n1 = pv1.getId(); 
    int n2 = pv2.getId(); 
    assertEquals("From: Date line: 79", n2-1, n1); 
  } // Generated by ComTest END
}