package printti.test;
// Generated by ComTest BEGIN
import java.io.File;
import printti.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.22 00:44:26 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class DatesTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa44 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa44() throws SailoException {    // Dates: 44
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(), pvm2 = new Pvm(); 
    assertEquals("From: Dates line: 48", 0, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 50", 1, dates.getLkm()); 
    dates.lisaa(pvm2); assertEquals("From: Dates line: 51", 2, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 52", 3, dates.getLkm()); 
    assertEquals("From: Dates line: 53", pvm1, dates.anna(0)); 
    assertEquals("From: Dates line: 54", pvm2, dates.anna(1)); 
    assertEquals("From: Dates line: 55", pvm1, dates.anna(2)); 
    assertEquals("From: Dates line: 56", false, dates.anna(1) == pvm1); 
    assertEquals("From: Dates line: 57", true, dates.anna(1) == pvm2); 
    try {
    assertEquals("From: Dates line: 58", pvm1, dates.anna(3)); 
    fail("Dates: 58 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    dates.lisaa(pvm1); assertEquals("From: Dates line: 59", 4, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 60", 5, dates.getLkm()); 
    dates.lisaa(pvm1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta151 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta151() throws SailoException {    // Dates: 151
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(); pvm1.luo(); 
    pvm1.setPvm("2025-04-23"); 
    Pvm pvm2 = new Pvm(); pvm2.luo(); 
    pvm2.setPvm("2025-04-24"); 
    Pvm pvm3 = new Pvm(); pvm3.luo(); 
    pvm3.setPvm("2025-04-25"); 
    String tiedNimi = "testdates"; 
    File ftied = new File(tiedNimi + ".dat"); 
    ftied.delete(); 
    try {
    dates.lueTiedostosta(tiedNimi); 
    fail("Expected SailoException was not thrown"); 
    } catch (SailoException e) {
    }
    try {
    dates.lisaa(pvm1); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm2); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.talleta(); 
    } catch (SailoException e) {
    fail("SailoException save: " + e.getMessage()); 
    }
    dates = new Dates(); 
    try {
    dates.lueTiedostosta(tiedNimi); 
    } catch (SailoException e) {
    fail("SailoException read: " + e.getMessage()); 
    }
    Iterator<Pvm> i = dates.iterator(); 
    assertEquals(pvm1.toString(), i.next().toString()); 
    assertEquals(pvm2.toString(), i.next().toString()); 
    assertEquals(pvm3.toString(), i.next().toString()); 
    assertFalse(i.hasNext()); 
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("Unexpected SailoException: " + e.getMessage()); 
    }
    try {
    dates.talleta(); 
    } catch (SailoException e) {
    fail("Unexpected SailoException save: " + e.getMessage()); 
    }
    assertTrue(ftied.delete()); 
    File fbak = new File(tiedNimi + ".bak"); 
    assertTrue(fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testDatesIterator298 
   * @throws NoSuchElementException when error
   */
  @Test
  public void testDatesIterator298() throws NoSuchElementException {    // Dates: 298
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(); 
    pvm1.parse("1|2025-04-23"); 
    Pvm pvm2 = new Pvm(); 
    pvm2.parse("2|2025-04-24"); 
    Pvm pvm3 = new Pvm(); 
    pvm3.parse("3|2025-04-25"); 
    try {
    dates.lisaa(pvm1); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm1: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm2); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm2: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm3: " + e.getMessage()); 
    }
    StringBuffer ids = new StringBuffer(); 
    for (Pvm pvm : dates) {
    ids.append(" ").append(pvm.getId()); 
    }
    assertEquals("From: Dates line: 334", " 1 2 3", ids.toString()); 
    ids = new StringBuffer(); 
    Iterator<Pvm> i = dates.iterator(); 
    while (i.hasNext()) {
    Pvm pvm = i.next(); 
    ids.append(" ").append(pvm.getId()); 
    }
    assertEquals("From: Dates line: 343", " 1 2 3", ids.toString()); 
    Iterator<Pvm> iter = dates.iterator(); 
    assertEquals("From: Dates line: 347", true, iter.next() == pvm1); 
    assertEquals("From: Dates line: 348", true, iter.next() == pvm2); 
    assertEquals("From: Dates line: 349", true, iter.next() == pvm3); 
    try {
    iter.next(); 
    fail("Dates: 352 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}