package printti.test;
// Generated by ComTest BEGIN
import java.io.File;
import printti.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.24 12:48:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class DatesTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa47 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa47() throws SailoException {    // Dates: 47
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(), pvm2 = new Pvm(); 
    assertEquals("From: Dates line: 51", 0, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 53", 1, dates.getLkm()); 
    dates.lisaa(pvm2); assertEquals("From: Dates line: 54", 2, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 55", 3, dates.getLkm()); 
    assertEquals("From: Dates line: 56", pvm1, dates.anna(0)); 
    assertEquals("From: Dates line: 57", pvm2, dates.anna(1)); 
    assertEquals("From: Dates line: 58", pvm1, dates.anna(2)); 
    assertEquals("From: Dates line: 59", false, dates.anna(1) == pvm1); 
    assertEquals("From: Dates line: 60", true, dates.anna(1) == pvm2); 
    try {
    assertEquals("From: Dates line: 61", pvm1, dates.anna(3)); 
    fail("Dates: 61 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    dates.lisaa(pvm1); assertEquals("From: Dates line: 62", 4, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 63", 5, dates.getLkm()); 
    dates.lisaa(pvm1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta134 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta134() throws SailoException {    // Dates: 134
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(); pvm1.luo(); 
    pvm1.setPvm("2025-04-23"); 
    Pvm pvm2 = new Pvm(); pvm2.luo(); 
    pvm2.setPvm("2025-04-24"); 
    Pvm pvm3 = new Pvm(); pvm3.luo(); 
    pvm3.setPvm("2025-04-25"); 
    String tiedNimi = "testdates"; 
    File ftied = new File(tiedNimi + ".dat"); 
    ftied.delete(); 
    try {
    dates.lueTiedostosta(tiedNimi); 
    fail("Expected SailoException was not thrown"); 
    } catch (SailoException e) {
    }
    try {
    dates.lisaa(pvm1); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm2); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("SailoException: " + e.getMessage()); 
    }
    try {
    dates.talleta(); 
    } catch (SailoException e) {
    fail("SailoException save: " + e.getMessage()); 
    }
    dates = new Dates(); 
    try {
    dates.lueTiedostosta(tiedNimi); 
    } catch (SailoException e) {
    fail("SailoException read: " + e.getMessage()); 
    }
    Iterator<Pvm> i = dates.iterator(); 
    assertEquals(pvm1.toString(), i.next().toString()); 
    assertEquals(pvm2.toString(), i.next().toString()); 
    assertEquals(pvm3.toString(), i.next().toString()); 
    assertFalse(i.hasNext()); 
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("Unexpected SailoException: " + e.getMessage()); 
    }
    try {
    dates.talleta(); 
    } catch (SailoException e) {
    fail("Unexpected SailoException save: " + e.getMessage()); 
    }
    assertTrue(ftied.delete()); 
    File fbak = new File(tiedNimi + ".bak"); 
    assertTrue(fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi268 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi268() throws SailoException {    // Dates: 268
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(); 
    pvm1.parse("1|2025-04-23"); 
    Pvm pvm2 = new Pvm(); 
    pvm2.parse("2|2025-04-24"); 
    Pvm pvm3 = new Pvm(); 
    pvm3.parse("3|2025-04-25"); 
    Pvm pvm4 = new Pvm(); 
    pvm4.parse("4|2025-04-26"); 
    try {
    dates.lisaa(pvm1); 
    } catch (SailoException e) {
    fail("SailoException adding pvm1: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm2); 
    } catch (SailoException e) {
    fail("SailoException adding pvm2: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("SailoException adding pvm3: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm4); 
    } catch (SailoException e) {
    fail("SailoException adding pvm4: " + e.getMessage()); 
    }
    Collection<Pvm> loytyneet = dates.etsi("", -1); 
    assertEquals("From: Dates line: 308", 4, loytyneet.size()); 
    Iterator<Pvm> i = loytyneet.iterator(); 
    assertEquals("From: Dates line: 310", pvm1.toString(), i.next().toString()); 
    assertEquals("From: Dates line: 311", pvm2.toString(), i.next().toString()); 
    assertEquals("From: Dates line: 312", pvm3.toString(), i.next().toString()); 
    assertEquals("From: Dates line: 313", pvm4.toString(), i.next().toString()); 
    assertEquals("From: Dates line: 314", false, i.hasNext()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testDatesIterator329 
   * @throws NoSuchElementException when error
   */
  @Test
  public void testDatesIterator329() throws NoSuchElementException {    // Dates: 329
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(); 
    pvm1.parse("1|2025-04-23"); 
    Pvm pvm2 = new Pvm(); 
    pvm2.parse("2|2025-04-24"); 
    Pvm pvm3 = new Pvm(); 
    pvm3.parse("3|2025-04-25"); 
    try {
    dates.lisaa(pvm1); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm1: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm2); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm2: " + e.getMessage()); 
    }
    try {
    dates.lisaa(pvm3); 
    } catch (SailoException e) {
    fail("Unexpected SailoException during adding pvm3: " + e.getMessage()); 
    }
    StringBuffer ids = new StringBuffer(); 
    for (Pvm pvm : dates) {
    ids.append(" ").append(pvm.getId()); 
    }
    assertEquals("From: Dates line: 365", " 1 2 3", ids.toString()); 
    ids = new StringBuffer(); 
    Iterator<Pvm> i = dates.iterator(); 
    while (i.hasNext()) {
    Pvm pvm = i.next(); 
    ids.append(" ").append(pvm.getId()); 
    }
    assertEquals("From: Dates line: 374", " 1 2 3", ids.toString()); 
    Iterator<Pvm> iter = dates.iterator(); 
    assertEquals("From: Dates line: 378", true, iter.next() == pvm1); 
    assertEquals("From: Dates line: 379", true, iter.next() == pvm2); 
    assertEquals("From: Dates line: 380", true, iter.next() == pvm3); 
    try {
    iter.next(); 
    fail("Dates: 383 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}