package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.13 00:20:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class DatesTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Dates: 29
    Dates dates = new Dates(); 
    Pvm pvm1 = new Pvm(), pvm2 = new Pvm(); 
    assertEquals("From: Dates line: 33", 0, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 34", 1, dates.getLkm()); 
    dates.lisaa(pvm2); assertEquals("From: Dates line: 35", 2, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 36", 3, dates.getLkm()); 
    assertEquals("From: Dates line: 37", pvm1, dates.anna(0)); 
    assertEquals("From: Dates line: 38", pvm2, dates.anna(1)); 
    assertEquals("From: Dates line: 39", pvm1, dates.anna(2)); 
    assertEquals("From: Dates line: 40", false, dates.anna(1) == pvm1); 
    assertEquals("From: Dates line: 41", true, dates.anna(1) == pvm2); 
    try {
    assertEquals("From: Dates line: 42", pvm1, dates.anna(3)); 
    fail("Dates: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    dates.lisaa(pvm1); assertEquals("From: Dates line: 43", 4, dates.getLkm()); 
    dates.lisaa(pvm1); assertEquals("From: Dates line: 44", 5, dates.getLkm()); 
    try {
    dates.lisaa(pvm1); 
    fail("Dates: 45 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}