package printti.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.17 00:15:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class PrinttiTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa39 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa39() throws SailoException {    // Printti: 39
    Printti printti = new Printti(); 
    Pvm aku1 = new Pvm(), aku2 = new Pvm(); 
    assertEquals("From: Printti line: 43", 0, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 44", 1, printti.getDates()); 
    printti.lisaa(aku2); assertEquals("From: Printti line: 45", 2, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 46", 3, printti.getDates()); 
    assertEquals("From: Printti line: 47", 3, printti.getDates()); 
    assertEquals("From: Printti line: 48", aku1, printti.annaPvm(0)); 
    assertEquals("From: Printti line: 49", aku2, printti.annaPvm(1)); 
    assertEquals("From: Printti line: 50", aku1, printti.annaPvm(2)); 
    try {
    assertEquals("From: Printti line: 51", aku1, printti.annaPvm(3)); 
    fail("Printti: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    printti.lisaa(aku1); assertEquals("From: Printti line: 52", 4, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 53", 5, printti.getDates()); 
    try {
    printti.lisaa(aku1); 
    fail("Printti: 54 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTodot81 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaTodot81() throws SailoException {    // Printti: 81
    Printti printti = new Printti(); 
    Pvm aku1 = new Pvm(), aku2 = new Pvm(), aku3 = new Pvm(); 
    int id1 = aku1.getId(); 
    int id2 = aku2.getId(); 
    Todo pitsi11 = new Todo(id1); printti.lisaa(pitsi11); 
    Todo pitsi12 = new Todo(id1); printti.lisaa(pitsi12); 
    Todo pitsi21 = new Todo(id2); printti.lisaa(pitsi21); 
    Todo pitsi22 = new Todo(id2); printti.lisaa(pitsi22); 
    Todo pitsi23 = new Todo(id2); printti.lisaa(pitsi23); 
    List<Todo> loytyneet; 
    loytyneet = printti.annaTodot(aku3); 
    assertEquals("From: Printti line: 97", 0, loytyneet.size()); 
    loytyneet = printti.annaTodot(aku1); 
    assertEquals("From: Printti line: 99", 2, loytyneet.size()); 
    assertEquals("From: Printti line: 100", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Printti line: 101", true, loytyneet.get(1) == pitsi12); 
    loytyneet = printti.annaTodot(aku2); 
    assertEquals("From: Printti line: 103", 3, loytyneet.size()); 
    assertEquals("From: Printti line: 104", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END
}