package printti.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.*;
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.24 14:14:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class PrinttiTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaTodot38 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaTodot38() throws SailoException {    // Printti: 38
    Printti printti = new Printti(); 
    Pvm pv1 = new Pvm(), pv2 = new Pvm(), pv3 = new Pvm(); 
    pv1.luo(); 
    pv2.luo(); 
    int id1 = pv1.getId(); 
    int id2 = pv2.getId(); 
    Todo pitsi11 = new Todo(id1); printti.lisaa(pitsi11); 
    Todo pitsi12 = new Todo(id1); printti.lisaa(pitsi12); 
    Todo pitsi21 = new Todo(id2); printti.lisaa(pitsi21); 
    Todo pitsi22 = new Todo(id2); printti.lisaa(pitsi22); 
    Todo pitsi23 = new Todo(id2); printti.lisaa(pitsi23); 
    List<Todo> loytyneet; 
    loytyneet = printti.annaTodot(pv3); 
    assertEquals("From: Printti line: 56", 0, loytyneet.size()); 
    loytyneet = printti.annaTodot(pv1); 
    assertEquals("From: Printti line: 58", 2, loytyneet.size()); 
    assertEquals("From: Printti line: 59", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Printti line: 60", true, loytyneet.get(1) == pitsi12); 
    loytyneet = printti.annaTodot(pv2); 
    assertEquals("From: Printti line: 62", 3, loytyneet.size()); 
    assertEquals("From: Printti line: 63", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa82 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa82() throws SailoException {    // Printti: 82
    Printti printti = new Printti(); 
    Pvm aku1 = new Pvm(), aku2 = new Pvm(); 
    assertEquals("From: Printti line: 86", 0, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 87", 1, printti.getDates()); 
    printti.lisaa(aku2); assertEquals("From: Printti line: 88", 2, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 89", 3, printti.getDates()); 
    assertEquals("From: Printti line: 90", 3, printti.getDates()); 
    assertEquals("From: Printti line: 91", aku1, printti.annaPvm(0)); 
    assertEquals("From: Printti line: 92", aku2, printti.annaPvm(1)); 
    assertEquals("From: Printti line: 93", aku1, printti.annaPvm(2)); 
    try {
    assertEquals("From: Printti line: 94", aku1, printti.annaPvm(3)); 
    fail("Printti: 94 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    printti.lisaa(aku1); assertEquals("From: Printti line: 95", 4, printti.getDates()); 
    printti.lisaa(aku1); assertEquals("From: Printti line: 96", 5, printti.getDates()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta152 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta152() throws SailoException {    // Printti: 152
    Printti printti = new Printti(); 
    Todos todos = new Todos(); 
    Pvm pvm1 = new Pvm(); pvm1.luo(); pvm1.setPvm("2025-04-23"); 
    Pvm pvm2 = new Pvm(); pvm2.luo(); pvm2.setPvm("2025-04-24"); 
    Todo todo = new Todo(pvm1.getId()); 
    todo.setTask("Tiskit"); 
    todo.setStatus(0); 
    todos.lisaa(todo); 
    Todo todo2 = new Todo(pvm1.getId()); 
    todo2.setTask("Pyykit"); 
    todo2.setStatus(1); 
    todos.lisaa(todo2); 
    Todo todo3 = new Todo(pvm2.getId()); 
    todo3.setTask("Astiat"); 
    todo3.setStatus(1); 
    todos.lisaa(todo3); 
    String directory = "testprintti"; 
    File dir = new File(directory); 
    File datesFile = new File(directory + "/dates.dat"); 
    File todosFile = new File(directory + "/todos.dat"); 
    dir.mkdir(); 
    datesFile.delete(); 
    todosFile.delete(); 
    try {
    printti.lueTiedostosta(directory); 
    fail("Printti: 184 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    printti.lisaa(pvm1); 
    printti.lisaa(pvm2); 
    printti.lisaa(todo); 
    printti.lisaa(todo2); 
    printti.lisaa(todo3); 
    printti.talleta(); 
    printti = new Printti();  // tekee uuden printin
    printti.lueTiedostosta(directory);  // lukee vanhat
    List<Pvm> dates = new ArrayList<>(); 
    for (int i = 0; i < printti.getDates(); i++) {
    dates.add(printti.annaPvm(i)); 
    }
    assertEquals("From: Printti line: 200", 2, dates.size()); 
    assertEquals("From: Printti line: 201", "2025-04-23", dates.get(0).getPvm()); 
    assertEquals("From: Printti line: 202", "2025-04-24", dates.get(1).getPvm()); 
    List<Todo> todosForPvm1 = printti.annaTodot(pvm1); 
    assertEquals("From: Printti line: 206", 2, todosForPvm1.size()); 
    assertEquals("From: Printti line: 207", "Tiskit", todosForPvm1.get(0).getTask()); 
    assertEquals("From: Printti line: 208", 0, todosForPvm1.get(0).getStatus()); 
    assertEquals("From: Printti line: 209", "Pyykit", todosForPvm1.get(1).getTask()); 
    assertEquals("From: Printti line: 210", 1, todosForPvm1.get(1).getStatus()); 
    List<Todo> todosForPvm2 = printti.annaTodot(pvm2); 
    assertEquals("From: Printti line: 214", 1, todosForPvm2.size()); 
    assertEquals("From: Printti line: 215", "Astiat", todosForPvm2.get(0).getTask()); 
    assertEquals("From: Printti line: 216", 1, todosForPvm2.get(0).getStatus()); 
    assertEquals("From: Printti line: 219", true, datesFile.delete()); 
    assertEquals("From: Printti line: 220", true, todosFile.delete()); 
    File datesBackupFile = new File(directory + "/dates.bak"); 
    File todosBackupFile = new File(directory + "/todos.bak"); 
    assertEquals("From: Printti line: 223", true, dir.delete()); 
  } // Generated by ComTest END
}