package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.24 12:52:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testParse78 */
  @Test
  public void testParse78() {    // Pvm: 78
    Pvm pvm1 = new Pvm(); 
    pvm1.parse("   2   | 2025-04-23"); 
    assertEquals("From: Pvm line: 81", 2, pvm1.getId()); 
    assertEquals("From: Pvm line: 82", "2|2025-04-23", pvm1.toString()); 
    Pvm pvm2 = new Pvm(); 
    pvm2.luo(); 
    int n = pvm2.getId(); 
    pvm2.parse("" + (n + 20) + "|2025-05-01"); 
    pvm2.luo(); 
    assertEquals("From: Pvm line: 89", n + 20 + 1, pvm2.getId()); 
    assertEquals("From: Pvm line: 90", "" + (n + 20 + 1) + "|2025-05-01", pvm2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLuo108 */
  @Test
  public void testLuo108() {    // Pvm: 108
    Pvm pv1 = new Pvm(); 
    assertEquals("From: Pvm line: 110", 0, pv1.getId()); 
    pv1.luo(); 
    Pvm pv2 = new Pvm(); 
    pv2.luo(); 
    int n1 = pv1.getId(); 
    int n2 = pv2.getId(); 
    assertEquals("From: Pvm line: 116", n2-1, n1); 
  } // Generated by ComTest END
}