package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.17 09:45:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class PvmTest {



  // Generated by ComTest BEGIN
  /** testLuo77 */
  @Test
  public void testLuo77() {    // Pvm: 77
    Pvm pv1 = new Pvm(); 
    assertEquals("From: Pvm line: 79", 0, pv1.getId()); 
    pv1.luo(); 
    Pvm pv2 = new Pvm(); 
    pv2.luo(); 
    int n1 = pv1.getId(); 
    int n2 = pv2.getId(); 
    assertEquals("From: Pvm line: 85", n2-1, n1); 
  } // Generated by ComTest END
}