package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.10 10:33:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TodoTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Todo: 72
    Todo pitsi1 = new Todo(); 
    assertEquals("From: Todo line: 74", 0, pitsi1.getId()); 
    pitsi1.rekisteroi(); 
    Todo pitsi2 = new Todo(); 
    pitsi2.rekisteroi(); 
    int n1 = pitsi1.getId(); 
    int n2 = pitsi2.getId(); 
    assertEquals("From: Todo line: 80", n2-1, n1); 
  } // Generated by ComTest END
}