package printti.test;
// Generated by ComTest BEGIN
import printti.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.22 00:55:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TodosTest {


  // Generated by ComTest BEGIN
  /** testIterator170 */
  @Test
  public void testIterator170() {    // Todos: 170
    Todos todot = new Todos(); 
    Todo todo21 = new Todo(2); todot.lisaa(todo21); 
    Todo todo11 = new Todo(1); todot.lisaa(todo11); 
    Todo todo22 = new Todo(2); todot.lisaa(todo22); 
    Todo todo12 = new Todo(1); todot.lisaa(todo12); 
    Todo todo23 = new Todo(2); todot.lisaa(todo23); 
    Iterator<Todo> i2=todot.iterator(); 
    assertEquals("From: Todos line: 182", todo21, i2.next()); 
    assertEquals("From: Todos line: 183", todo11, i2.next()); 
    assertEquals("From: Todos line: 184", todo22, i2.next()); 
    assertEquals("From: Todos line: 185", todo12, i2.next()); 
    assertEquals("From: Todos line: 186", todo23, i2.next()); 
    try {
    assertEquals("From: Todos line: 187", todo12, i2.next()); 
    fail("Todos: 187 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int ids[] = { 2,1,2,1,2} ; 
    for (Todo task:todot) {
    assertEquals("From: Todos line: 193", ids[n], task.getDate()); 
    n++; 
    }
    assert n == ids.length : "Käsittelemättmiä todo, tarkasta"; 
    assertEquals("From: Todos line: 197", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTodot211 */
  @Test
  public void testAnnaTodot211() {    // Todos: 211
    Todos todot = new Todos(); 
    Todo pitsi21 = new Todo(2); todot.lisaa(pitsi21); 
    Todo pitsi11 = new Todo(1); todot.lisaa(pitsi11); 
    Todo pitsi22 = new Todo(2); todot.lisaa(pitsi22); 
    Todo pitsi12 = new Todo(1); todot.lisaa(pitsi12); 
    Todo pitsi23 = new Todo(2); todot.lisaa(pitsi23); 
    Todo pitsi51 = new Todo(5); todot.lisaa(pitsi51); 
    List<Todo> loytyneet; 
    loytyneet = todot.annaTodot(3); 
    assertEquals("From: Todos line: 224", 0, loytyneet.size()); 
    loytyneet = todot.annaTodot(1); 
    assertEquals("From: Todos line: 226", 2, loytyneet.size()); 
    assertEquals("From: Todos line: 227", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Todos line: 228", true, loytyneet.get(1) == pitsi12); 
    loytyneet = todot.annaTodot(5); 
    assertEquals("From: Todos line: 230", 1, loytyneet.size()); 
    assertEquals("From: Todos line: 231", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}