package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.04.17 13:48:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TodoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Todo: 72
    Todo todo1 = new Todo(); 
    assertEquals("From: Todo line: 74", 0, todo1.getId()); 
    todo1.rekisteroi(); 
    Todo todo2 = new Todo(); 
    todo2.rekisteroi(); 
    int n1 = todo1.getId(); 
    int n2 = todo2.getId(); 
    assertEquals("From: Todo line: 80", n2-1, n1); 
  } // Generated by ComTest END
}