package printti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import printti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.05.22 00:52:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TodoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Todo: 102
    Todo todo1 = new Todo(); 
    assertEquals("From: Todo line: 104", 0, todo1.getId()); 
    todo1.rekisteroi(); 
    Todo todo2 = new Todo(); 
    todo2.rekisteroi(); 
    int n1 = todo1.getId(); 
    int n2 = todo2.getId(); 
    assertEquals("From: Todo line: 110", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString144 */
  @Test
  public void testToString144() {    // Todo: 144
    Todo todo = new Todo(); 
    todo.parse("   2   |  2  |   Kalastus  | 0  "); 
    assertEquals("From: Todo line: 147", "2|2|Kalastus|0", todo.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse160 */
  @Test
  public void testParse160() {    // Todo: 160
    Pvm pvm1 = new Pvm(); 
    pvm1.parse("   2   | 2025-04-23"); 
    assertEquals("From: Todo line: 163", 2, pvm1.getId()); 
    assertEquals("From: Todo line: 164", "2|2025-04-23", pvm1.toString()); 
    Pvm pvm2 = new Pvm(); 
    pvm2.luo(); 
    int n = pvm2.getId(); 
    pvm2.parse("" + (n + 20) + "|2025-05-01"); 
    pvm2.luo(); 
    assertEquals("From: Todo line: 171", n + 20 + 1, pvm2.getId()); 
    assertEquals("From: Todo line: 172", "" + (n + 20 + 1) + "|2025-05-01", pvm2.toString()); 
  } // Generated by ComTest END
}